### PR TITLE
use bounds formatoption widget for colors dialog

### LINKED ISSUE #7: NEW FEATURE: Implement better selection of colormap
#### Summary
There are way more colormaps available and it would be nice to select them independent from the current push button

#### Reason

more freedom

#### Detailed explanation
One possibility (and probably the easiest) would be to include a colormap dialog as it is already implemented for psy-simple (see Screenshot below) for the psyplot-gui. @tobstac: Do you think this is appropriate or do you have any other ideas?

#### Examples
Screenshot from 2020-04-14 17-00-36

### PR DESCRIPTION
**Pull request by Chilipp**
This commit revises the color settings dialog and uses the bounds formatoption dialog. We additionally added a live-updating preview of the resulting colorbar

@tobstac: It would be nice of you could have a look at it on mybinder and give me some feedback :smiley: [Binder](https://mybinder.org/v2/gh/psyplot/psy-view/bounds-dialog?urlpath=%2Fdesktop) I also added a discrete logarithmic option

This PR integrates with https://github.com/psyplot/psy-simple/pull/14

- [x] implemented better selection of colormaps
- [x] Tests added (for all bug fixes or enhancements)
- [x] Tests passed (for all non-documentation changes)
- [x] revert 8ffe4c9e763ce85298927b4e39f261972330160b
 
Closes #7

### CODE REVIEW

**Comment by tobstac** [comment]
Great work! It does look nice and it quite intuitive to use, so I would consider it done. I though for a moment about the fact that the displayed colorbar is unchanged and the labels (and maps of course) adapt to the scaling as opposed to ncview where the colorbar changes while the labels stay static. I'd say ncview is more intuitive here at first, but when you want plots which are easier to analyse, your way very much helps to actually relate the color you are seeing to a specific number. Thus, I would stick to it.

**Comment by Chilipp** [comment]
Thanks for the feedback @tobstac! :) My plan was anyway to also add an option for the colorbar ticks. Then you can fix the. The default at the moment is to let matplotlib choose the default, and this varies of course depending on the norm you use

**Comment by Chilipp** [comment]
Hey @tobstac, @StefanHagemann and @psyplot/psyplot-hzg in general! I revised the color settings dialog (and more) and it would be nice if you could give it a try here:  [Binder](https://mybinder.org/v2/gh/psyplot/psy-view/bounds-dialog?urlpath=%2Fdesktop). @StefanHagemann: is this easy enough for the range option you mentioned?

Unfortunately, mybinder did not recreate a new container but uses the outdated version of psy-simple, etc. Therefore, as soon as you see the desktop, open the terminal by clicking on the 
image button at the bottom and type

```bash
conda update -c psyplot/label/bounds-dialog psy-simple psy-maps -y
```

When this has finished, please open one of the netCDF files. It would be nice to get your feedback on the color options, and whether this is intuitive and rich enough

image

**Note:** You can actually also edit the individual colors of a colormap now to customize it more. Just click the *Edit* button in the color settings dialog and double-click a color to edit it

**Comment by tobstac** [comment]
That's really nice progress! I just played around with your new colormap and ticks options and I've seen every last level of detail can be controlled to produce any kind of colormap scaling with correspondent ticks. I have the impression that the automatic bounds and scalings work best in the linear case but I don't mind having to do some typing for special custom colormaps. So thanks a lot, in my opinion its perfect!

**Pull request merged**
