### PR TITLE
NEW FEATURE: Implement handling of multiple plots

### LINKED ISSUE #15: New Feature: multi-page pdf
#### Problem description

Psy-plot support a range of output formats including pdf. However, every panel needs to be exported in a single file.

#### Expected Output
It would be preferable to be able to select panels and export them to a multi-page pdf. It would be even better, if the actual export does not happen when the panel is selected for export, but as a final step. For example, if I prepare several panels and realize with the last one that I forgot something in all the others, I could simply add the information to the still accessible panels, instead of having to reproduce all of them again.

### PR DESCRIPTION
**Pull request by Chilipp**
This PR implements the creation and handling of multiple plots within the psy-view widget. You can now select, which plot should be modified and loaded by the widget, and you can export all open plots to a single file.

Closes #15 

 - [x] Tests added (for all bug fixes or enhancements)
 - [ ] Tests passed (for all non-documentation changes)

@tobstac: I still have to add some tests, but could you nonetheless try and tell me, whether you are satisfied with it? Just click on [Binder](https://mybinder.org/v2/gh/Chilipp/psy-view/master?urlpath=%2Fdesktop)

### CODE REVIEW

**Comment by tobstac** [comment]
Same as you I couldn't check the resulting pdf in the noVNC. However, in terms of export functionality it seems fine, thanks a lot! Btw. I accidentially exported all panel into a png without any error message. I couldn't check the png on binder, but how would it look like? To my knowledge there is no multipage png available, thus I guess it is just the first or last panel or something like it?

**Comment by Chilipp** [comment]
Hey @tobstac! Yes, this is possible and without any option, this would save one figure, and then overwrite this with the next open figure. It uses the [Project.export](https://psyplot.readthedocs.io/en/latest/api/psyplot.project.html#psyplot.project.Project.export) method. As such, if your filename would be like `myplot-%i.png`, it would create figures like `myplot-1.png`, `myplot-2.png`, etc.

This should eventually be documented, you are right

**Comment by Chilipp** [comment]
or should I ask for an image file for every open figure?

**Comment by tobstac** [comment]
Aha, this is a nice feature. Better don't ask for a new filename every time. As soon as this feature is documented it very useful!

**Comment by Chilipp** [comment]
alright, thanks for the feedback :smiley:

**Comment by Chilipp** [comment]
by the way @tobstac: concerning the issue of downloading the PDFs (I just played around a bit). You can actually download it.

As soon as you see the desktop in your browser, your URL should be something like

```
https://hub.gke.mybinder.org/user/chilipp-psy-view-<irgendwas>/desktop/?token=<TOKEN>
```

if you then simply delete the `/desktop` from the URL, you will see the standard notebook server and the files that you saved to the desktop are in the `Desktop` folder. Does this work?

**Pull request merged**
