### PR TITLE
Presets

### LINKED ISSUE #3: NEW FEATURE: Allow to add formatoption presets
#### Summary
It should be able to import/export presets, i.e. YAML-formatted mappings from formatoption key to value

#### Reason
This allows to customize the plot easily for recurring tasks or data files.

#### Detailed explanation
A preset file should look like

```yaml
title: "{desc}"
mapplot:
  projection: "ortho"
lineplot:
  color: "k"
```

### PR DESCRIPTION
**Pull request by Chilipp**
closes #3 

This PR builds upon psyplot/psyplot#24 and psyplot/psyplot-gui#17 and implements the preset functionality into psy-view. We add a tool-button with a menu to save and load the current plot settings as a preset
image  

 - [x] Tests added (for all bug fixes or enhancements)
 - [ ] Tests passed (for all non-documentation changes)

### CODE REVIEW

**Comment by Chilipp** [comment]
Hey @psyplot/psyplot-hzg, I'd highly appreciate some quick feedback on the presets option before I merge this into the master branch and install it on mistral, etc.. Would you have time to do so?

Just 

1. click on [Binder](https://mybinder.org/v2/gh/psyplot/psy-view/presets?urlpath=%2Fdesktop) 
2. as soon as you see the desktop, open one of the netCDF files (double-click `icon-test.nc` for instance)
3. make a plot of a variable, `t2m` for instance
3. load a preset with the `Preset` button (see screenshot in the comment above, one preset is already preset installed: `EUR-temperature`.
5. Tell me what you think :smiley:

**Comment by tobstac** [comment]
I just tried it. The functionality seems to work fine and it is definitely a useful feature.
However, it seems to open_directory icon in the psy-view GUI (upper right) has been replaced by a red cross which is somewhat counter-intuitive. Also I expected the names of the colormap and projection to change when loading a preset, however, it still showed the standard colormap name even though the preset used another. Might be nice if this information could be made consistent.

**Comment by Chilipp** [comment]
thanks @tobstac! 

> However, it seems to open_directory icon in the psy-view GUI (upper right) has been replaced by a red cross which is somewhat counter-intuitive.

Not sure, what you mean exactly. Can you make a screenshot and paste it here?

> Also I expected the names of the colormap and projection to change when loading a preset, however, it still showed the standard colormap name even though the preset used another. Might be nice if this information could be made consistent.

True, I'll implement this, thanks for spotting it :sweat_smile:

**Comment by Chilipp** [comment]
ah, is it this one @tobstac? 
image
Yes, the red cross should actually be hidden on the start

**Comment by Chilipp** [comment]
ok, sollte jetzt funktionieren @tobstac 

[Binder](https://mybinder.org/v2/gh/psyplot/psy-view/presets?urlpath=%2Fdesktop)

**Comment by tobstac** [comment]
> Not sure, what you mean exactly. Can you make a screenshot and paste it here?

psyview

The one at the upper right corner. I think up to now there was a small directory symbol there.

**Comment by Chilipp** [comment]
oh thanks! This happened in a22db85e172fd3ca5c62b3d4607c0bbcb2d1a0ec, no clue why. I'll fix it

**Comment by Chilipp** [comment]
done with 2989627 @tobstac 

[Binder](https://mybinder.org/v2/gh/psyplot/psy-view/presets?urlpath=%2Fdesktop)

any more comments?

**Comment by tobstac** [comment]
Nope, seems all shiny to me. As I said, nice new feature :+1:

**Pull request merged**
