### PR TITLE
add projection button as a menu

### LINKED ISSUE #9: CHANGE FEATURE: include more possibilities to select the projections
#### Summary
The pushbutton to select the projection should be replaced or extended by a better control.

#### Reason
The button is rather uncomfortable and slow, and it limits the available projections. 

#### Detailed explanation
The basemap is handled via the [projection](https://psyplot.readthedocs.io/projects/psy-maps/en/latest/api/psy_maps.plotters.html#psy_maps.plotters.FieldPlotter.projection) formatoption that can have strings or [cartopy projections](https://scitools.org.uk/cartopy/docs/latest/crs/projections.html). Now idea what the best solution is here to include it in the GUI. Any idea @tobstac?

### PR DESCRIPTION
**Pull request by Chilipp**
and add projection button value to initialization fmts

Closes #9

 - [x] Tests passed (for all non-documentation changes)

@tobstac: Could you try and tell me, whether you are satisfied with it? Just click on [Binder](https://mybinder.org/v2/gh/Chilipp/psy-view/projections?urlpath=%2Fdesktop)

### CODE REVIEW

**Comment by tobstac** [comment]
In terms of functionality, I am very happy with this solution. Just one more comment, as you aim to make the gui as intuitive a possible. I'd probably not try to hold the button for a given time without anyone telling me before. Still, as there is this small downwards arrow in the box I would expect to get a drop down menu. Thus my first instinct (after not getting the list with a left click) to try the right mouse bottom. So my recommenation would be to open the drop down menu with the normal left click - you anyway only save time if you know beforehand that the very next projection is the one you need and selecting one out of a list a 5 (and maybe even ten if people request additional projections later) does not take much time. Alternatively, if you want to keep this cycle-through feature - maybe for users who are uncertain which projection would be best - could you change the drop down to the right mouse bottom instead of holding the left one? I think it is just more common.

**Comment by Chilipp** [comment]
true. Taking the right-button sounds like a good plan! I'd stick to the clicking because this is easier to iteratively go through the projections to try them out without the need to always go through the dropdown menu.

**Comment by tobstac** [comment]
Then maybe you could make the implementation for [https://github.com/psyplot/psy-view/issues/7](url) in a similar way?

**Comment by Chilipp** [comment]
Yes, good idea! Actually, what do you think about this solution?

Screenshot 2020-04-16 12:37:58

This is even simpler to implement and, I think, absolutely intuitive.
If you click on the button, you select the next projection, if you click on the arrow, you see the available options.

**Comment by tobstac** [comment]
Perfect!!

**Comment by Chilipp** [comment]
Alright, done with https://github.com/psyplot/psy-view/pull/13/commits/661e3ecf1cbbf5b70308b13831c2f32fae857d95. You can watch it following the same link as before: [Binder](https://mybinder.org/v2/gh/Chilipp/psy-view/projections?urlpath=%2Fdesktop)

**Comment by Chilipp** [comment]
I'll merge this PR when the tests are finished and delete this branch (i.e. the binder links will become invalid when this PR is merged)

**Pull request merged**
